# Generated by Django 3.2.7 on 2021-09-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Числовой'), ('string', 'Строковый'), ('wysiwyg', 'Редактор'), ('textArea', 'Текстовое поле'), ('text', 'текст')], default='int', max_length=150, verbose_name='Тип поля')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('selector', models.CharField(max_length=150, verbose_name='Селектор')),
                ('key', models.SlugField(max_length=150, verbose_name='Key')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('fields', models.ManyToManyField(blank=True, null=True, related_name='terms_fields', to='wordpress.Fields')),
                ('parentTerm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='wordpress.terms')),
                ('postTypes', models.ManyToManyField(blank=True, null=True, related_name='terms_types', to='wordpress.Types')),
            ],
        ),
        migrations.CreateModel(
            name='FieldsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_field', to='wordpress.fields', verbose_name='Поле')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_post', to='wordpress.types', verbose_name='Запись')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_term', to='wordpress.terms', verbose_name='Таксономия')),
            ],
        ),
        migrations.AddField(
            model_name='fields',
            name='entityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_type', to='wordpress.types', verbose_name='Тип записи'),
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_type', to='wordpress.types', verbose_name='Тип записи')),
            ],
        ),
    ]
