# Generated by Django 3.2.7 on 2021-09-30 16:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Числовой'), ('string', 'Строковый'), ('wysiwyg', 'Редактор'), ('textArea', 'Текстовое поле'), ('text', 'текст'), ('link', 'Ссылка')], default='int', max_length=150, verbose_name='Тип поля')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('selector', models.CharField(max_length=150, verbose_name='Селектор')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
                'ordering': ['title', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тип записи',
                'verbose_name_plural': 'Типы записей',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('category', 'category'), ('tag', 'tag')], default='category', max_length=8, verbose_name='Тип таксономии')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('fields', models.ManyToManyField(blank=True, related_name='terms_fields', to='wordpress.Fields')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wordpress.terms')),
                ('postTypes', models.ManyToManyField(blank=True, related_name='terms_types', to='wordpress.Types')),
            ],
            options={
                'verbose_name': 'Таксономия',
                'verbose_name_plural': 'Таксономии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FieldsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Значение')),
                ('key', models.SlugField(max_length=150, verbose_name='Ключ-внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_field', to='wordpress.fields', verbose_name='Поле')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_post', to='wordpress.types', verbose_name='Запись')),
                ('term', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_term', to='wordpress.terms', verbose_name='Таксономия')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
                'ordering': ['field', 'post', 'term'],
            },
        ),
        migrations.AddField(
            model_name='fields',
            name='entityType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields_type', to='wordpress.types', verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='fields',
            name='termType',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields_term', to='wordpress.terms', verbose_name='Тип Таксономии'),
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('terms', models.ManyToManyField(related_name='entities_terms', to='wordpress.Terms', verbose_name='Категории,теги')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_type', to='wordpress.types', verbose_name='Тип записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['title'],
            },
        ),
    ]
