# Generated by Django 3.2.7 on 2021-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entities',
            options={'ordering': ['title'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ['title'], 'verbose_name': 'Тип записи', 'verbose_name_plural': 'Типы записей'},
        ),
        migrations.AddField(
            model_name='terms',
            name='type',
            field=models.CharField(choices=[('category', 'Категория'), ('tag', 'Тег')], default='category', max_length=8, verbose_name='Тип таксономии'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='terms_fields', to='wordpress.Fields'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='postTypes',
            field=models.ManyToManyField(blank=True, related_name='terms_types', to='wordpress.Types'),
        ),
    ]
