# Generated by Django 3.2.7 on 2021-09-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0002_auto_20210910_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'ordering': ['title', 'type'], 'verbose_name': 'Поле', 'verbose_name_plural': 'Поля'},
        ),
        migrations.AlterModelOptions(
            name='fieldsvalues',
            options={'ordering': ['field', 'post', 'term'], 'verbose_name': 'Поле', 'verbose_name_plural': 'Поля'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ['title'], 'verbose_name': 'Таксономия', 'verbose_name_plural': 'Таксономии'},
        ),
        migrations.AlterField(
            model_name='fieldsvalues',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_post', to='wordpress.types', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='fieldsvalues',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_term', to='wordpress.terms', verbose_name='Таксономия'),
        ),
    ]
