# Generated by Django 3.2.7 on 2021-09-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20210930_1332'),
        ('wordpress', '0002_types_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='photologue.photo', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='terms',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='photologue.photo', verbose_name='Изображение'),
        ),
    ]
