# Generated by Django 3.2.7 on 2021-10-03 12:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0003_auto_20210930_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
