# Generated by Django 3.2.7 on 2021-09-10 13:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0003_auto_20210910_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
