# Generated by Django 3.2.7 on 2021-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0004_alter_entities_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='terms',
            field=models.ManyToManyField(related_name='entities_terms', to='wordpress.Terms', verbose_name='Категории,теги'),
        ),
    ]
