# Generated by Django 3.2.7 on 2021-09-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0006_auto_20210916_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='termType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fields_term', to='wordpress.terms', verbose_name='Тип Таксономии'),
            preserve_default=False,
        ),
    ]
