# Generated by Django 3.2.7 on 2021-09-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0007_fields_termtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='entityType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields_type', to='wordpress.types', verbose_name='Тип записи'),
        ),
    ]
