# Generated by Django 3.2.7 on 2021-09-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0008_alter_fields_entitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='termType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields_term', to='wordpress.terms', verbose_name='Тип Таксономии'),
        ),
    ]
