# Generated by Django 3.2.7 on 2021-09-25 09:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0010_auto_20210916_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={},
        ),
        migrations.AddField(
            model_name='terms',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terms',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terms',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terms',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fields',
            name='termType',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields_term', to='wordpress.terms', verbose_name='Тип Таксономии'),
        ),
        migrations.AlterField(
            model_name='fieldsvalues',
            name='term',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsValues_term', to='wordpress.terms', verbose_name='Таксономия'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='parentTerm',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wordpress.terms'),
        ),
    ]
