# Generated by Django 3.2.7 on 2021-09-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0011_auto_20210925_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms',
            old_name='parentTerm',
            new_name='parent',
        ),
    ]
