# Generated by Django 3.2.7 on 2021-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0012_rename_parentterm_terms_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ['title'], 'verbose_name': 'Таксономия', 'verbose_name_plural': 'Таксономии'},
        ),
        migrations.AlterField(
            model_name='terms',
            name='type',
            field=models.CharField(choices=[('category', 'category'), ('tag', 'tag')], default='category', max_length=8, verbose_name='Тип таксономии'),
        ),
    ]
